package io.github.kamitejp.recognition;

public enum RecognitionOpError {
  OCR_UNAVAILABLE,
  SCREENSHOT_API_COMMUNICATION_FAILED,
  SELECTION_CANCELLED,
  SELECTION_FAILED,
  SCREENSHOT_FAILED,
  INPUT_TOO_SMALL,
  OCR_ERROR,
  ZERO_VARIANTS
}
